### ISSUE TITLE
transform keyword allows a string to be modified before validation

### ISSUE THREAD

**Issue by slavakam** [epoberezkin/ajv-keywords#100]
I wrote schema where 3 properties in object are strings with minLength = 1 and transform['trim']

I'll expect that ajv(6.10.0) with ajv-keywords(3.4.0) will throw error for lastName and nickname properties. But ajv threw error only for lastName.

In your documentation you said that transform modified data before validation.

https://codesandbox.io/s/6r9g1

**Comment by epoberezkin** [comment]
For it to be modified before validation you need to make it run before validation using allOf keyword.

**Comment by epoberezkin** [comment]
Readme can be made clearer, with some example.
