### ISSUE TITLE
Using select with json objects

### ISSUE THREAD

**Issue by Altoblond** [epoberezkin/ajv-keywords#103]
Hello,
Is it possible to use the select keyword with json objects? The example explains how to apply a select case to a string property:
```
    {kind: 'foo', foo: 'any'},
    {kind: 'bar', bar: 1},
```
where 'kind' is the property used to determine the select cases.

Would it be possible to have a select case for a json object written this way instead:

```
{
    foo:
    {
        foo:'any'
    },
    bar:
    {
        bar:1
    }
}
```

**Comment by epoberezkin** [comment]
I don't understand the use case and the idea. It would help if you post some test case - the schema and the data samples that pass and fail.

**Comment by Altoblond** [comment]
Of course, see example below:

`var Ajv = require('ajv');
var AjvKeywords = require('ajv-keywords');

const ajv = new Ajv({
    $data: true,
    messages: true,
    verbose: true,
    allErrors: true
});

AjvKeywords(ajv);

var schema = {
    type: 'object',
    properties: {
        a: {
            type: 'object',
            title: 'a',
            required: ["attr1", "attr2", "attr3"],
            properties: {attr1: {type: "string"}, attr2: {type: "number"}, attr3: {type: ["string", "number"]}},
            additionalProperties: false
        },
        b: {
            type: 'object',
            title: 'b',
            required: ["attr1", "attr2"],
            properties: {attr1: {type: "string"}, attr2: {type: "number"}},
            additionalProperties: false
        },
    },
    additionalProperties: false
};

var validDataList = [
    {a: {attr1: "toto", attr2: 4, attr3: 8}},
    {b: {attr1: "toto", attr2: 4}},
    {
        a: {attr1: "toto", attr2: 4, attr3: 8},
        b: {attr1: "toto", attr2: 4, attr3: 8}
    }
];

var invalidDataList = [
    {a: {attr2: 4, attr3: 8}},
    {b: {attr1: "toto", attr2: "hello"}},
    {
        a: {attr1: "toto", attr2: 4, attr3: 8},
        b: {attr1: "toto", attr2: 4, attr3: 8},
        unknown: {attr1: "toto", attr2: 4, attr3: 8}
    }
];

let validate = ajv.compile(schema);

for (const current of validDataList) {
    validate = ajv.compile(schema);
    console.log('========');
    console.log(current);
    const valid = validate(current);

    if (!valid) {
        console.log(validate.errors);
    }
}
for (const current of invalidDataList) {
    console.log('========');
    console.log(current);
    const valid = validate(current);

    if (!valid) {
        console.log(validate.errors);
    }
}
`

In this example all items in validDataList are correct, all examples in invalidDataList display errors.
Now I would like to add an additional rule for valid schema to contain either an item of type 'a' or an item of type 'b' but not both.
OneOf does not fully answer my need because if either a or b is malformatted the logged error indicates that provided data is neither a 'a' or a 'b' but does not help pointing to the actual malformatting error.
Select seems to be the right solution but in the example provided it uses an attribute of an object to determine the select case. In my case in need to use the type of the instance of my object:

```
    {a: {attr1: "toto", attr2: 4, attr3: 8}}, // valid
    {b: {attr1: "toto", attr2: 4}}, // valid
    {a: {attr1: "toto", attr2: 4, attr3: 8}, b: {attr1: "toto", attr2: 4, attr3: 8}} // invalid
```

**Comment by epoberezkin** [comment]
It is not related to "select" keyword - combination of "required" and "anyOf" should do it. It is a general JSON Schema usage question - please submit to StackOverflow.
