### ISSUE TITLE
uniqueItemProperties is not working 

### ISSUE THREAD

**Issue by Diana131194** [epoberezkin/ajv-keywords#107]
Hi,
i am trying to use the "uniqueItemProperties" keyword in a json scema like this:
{
    "type": "array",
    "uniqueItemProperties": ["username"],
    "items": {
        "type": "object", 
        "required": [
            "username",
            "email"   
        ],
        "properties": {
			"id": {
				"type": "integer"
			},
			"username": {
				"type": "string"
			},
			"email": {
				"type": "string",
				"format": "email"
			}
		}
	}
}

But, when i am using this schema on a json that has 2 objects with the same username the validation function return true.
Any ideas what am i missing? 

Thanks

**Comment by epoberezkin** [comment]
Difficult to say without the code sample. You may have missed adding the keyword to ajv instance

**Comment by Diana131194** [comment]
Here is the code sample in my project:

const Ajv = require('Ajv');
const ajv = new Ajv();
const normalise = require('ajv-error-messages');
const schema = require('./schema.json');
require("ajv-keywords")(ajv, ["uniqueItemProperties"])

const validate = ajv.compile(schema);
var start = new Date().getTime();   
const valid = validate(data);
var end = new Date().getTime();
console.log((end - start) + " milliseconds");

Thank you!

**Comment by epoberezkin** [comment]
Looks correct. Please submit something that can be executed to runkit.com - I.e. without private dependencies, with data object. Are you sure that the data you pass is the array? And that the environment you are in parses JSON correctly in require? Anyway, full sample in run kit will allow to understand what is wrong.

**Comment by Diana131194** [comment]
Thank you for your help, i see now that it works.
I have another question.
Can i check a uniqueness of two entries together?
For example, if i want the key of the object to be the username **and** the email (so if only the username is duplicated in 2 objects it's ok, but if the username and the email is duplicate in 2 objects it is not ok).
Is it possible to check something like this with the Ajv?
Thank you!

**Comment by syahiaoui** [comment]
Hi @epoberezkin,
Is it possible to use unqiueItem, with complexe json schema: 

```js
const Ajv = require('ajv');
const ajv = new Ajv();
require("ajv-keywords")(ajv, ["uniqueItemProperties"])

const validate = ajv.compile({
    "title": "entity",
    "description": "entity descriptions",
    "required": ["cui", "site", "inforamtionsList"],
    "properties": {
        "site": {
            "type": "object",
            "title": "Site",
            "keys": [
                "site",
                "siteType",
                "country"
            ],
            "required": [
                "site",
                "siteType",
                "country"
            ],
            "properties": {
                "country": {
                    "type": "string",
                    "title": "",
                    "description": ""
                },
                "site": {
                    "type": "string",
                    "title": "",
                    "description": ""
                },
                "siteType": {
                    "type": "string",
                    "title": "",
                    "description": ""
                }
            }
        },
        "location": {
            "type": "string",
            "title": "",
            "description": ""
        },

        "inforamtionsList": {
            "type": "array",
            "uniqueItemProperties": ["username"],
            "items": {
                "type": "object",
                "required": [
                    "username",
                    "email"
                ],
                "properties": {
                    "id": {
                        "type": "integer"
                    },
                    "username": {
                        "type": "string"
                    },
                    "email": {
                        "type": "string",
                        "format": "email"
                    }
                }
            }
        }
    }
});
const data = [
    { id: 1, username: "jss", email: 'ys@gmail.com' },
    { id: 2, username: "jss", email: 'ys@gmail.com' },
    { id: 3, username: "jssss", email: 'ys@gmail.com' }
];
const valid = validate(data);
if (!valid) console.log(validate.errors);
console.log("Success: " + valid);
```

I tried this but evry time it return validation success, i suspect validation error.


Thank's
samir

**Comment by epoberezkin** [comment]
@Diana131194 this is not how keyword is defined, it expects each property to have unique values across all items, not the combination of properties.

You can extend this keyword to accept arrays of strings in addition to strings as items in the array to pass to the keyword. So in your case the schema would look like: ```{"uniqueItemProperties": [["email", "username"]]}```

If it is not a massive complication it can be merged - I suggest submitting a separate issue with a feature proposal to extend it if you are going to implement it.

**Comment by SimonKlausLudwig** [comment]
Any update on this feature.

**Comment by atng** [comment]
Implimented in PR [here](https://github.com/ajv-validator/ajv-keywords/pull/386) @SimonKlausLudwig @Diana131194
