### ISSUE TITLE
Error when not passing a value to "keyword" parameter

### ISSUE THREAD

**Issue by amjedomar** [epoberezkin/ajv-keywords#111]
The [document ](https://github.com/epoberezkin/ajv-keywords#usage) refers that I can add all keywords by not passing a value to `keyword` parameter
```
const Ajv = require('ajv');
const ajv = new Ajv();
require('ajv-keywords')(ajv);
```
But when I do that I got this error
```
keyword select requires $data option
```

**Comment by epoberezkin** [comment]
select keyword requires that Ajv instance has option $data: true.

**Comment by amjedomar** [comment]
oh yeah that solved the problem
```
const Ajv = require('ajv');
const ajv = new Ajv({ $data: true });
require('ajv-keywords')(ajv);
```
it works

**Comment by epoberezkin** [comment]
The example needs to be updated - thank you
