### ISSUE TITLE
[Feature Request] Error object should expose the value of `typeof`

### ISSUE THREAD

**Issue by ulivz** [epoberezkin/ajv-keywords#114]
# Actual

- Code: 

```js
const Ajv = require('ajv')
const ajv = new Ajv()
require('ajv-keywords')(ajv);

const valid = ajv.validate({
  "properties": {
    "fn": {
      "typeof": "function"
    }
  }
}, {
  fn: 1
})

console.log(valid)
console.log(ajv.errors)

```

- Output: 

```
false
[ { keyword: 'typeof',
    dataPath: '.fn',
    schemaPath: '#/properties/fn/typeof',
    params: { keyword: 'typeof' },
    message: 'should pass "typeof" keyword validation' } ]
```

We can get the value of `typeof` in the error object.

# Expected

User should be able to access the value of `typeof` in the error object so that they can custom the error message.

**Comment by epoberezkin** [comment]
@ulivz the error object contains JSON pointer reference to the schema location where it is located, you can also include the schema part with verbose option of Ajv instance
