### ISSUE TITLE
uniqueItemProperties throws an error

### ISSUE THREAD

**Issue by DmitryMyadzelets** [epoberezkin/ajv-keywords#23]
The below code throws the error: `TypeError: equal is not a function`.

```javascript
const ajv = require('ajv')();
require('ajv-keywords')(ajv);

ajv.validate({
    properties: {
        array: {
            type: 'array',
            uniqueItemProperties: ['id']
        }
    }
}, {
    array: [{
        id: 0
    }, {
        id: 0
    }]
})
```

**Comment by epoberezkin** [comment]
Works for me: https://runkit.com/esp/594d7bfee561c60012f2e5cf

**Comment by DmitryMyadzelets** [comment]
Well, I've updated `ajv@5.0.1` to `ajv@5.2.1`, and it work for me too, now.

**Comment by epoberezkin** [comment]
So to make things easier:
- [ ] add issue template etc. from ajv
- [ ] make peerDependency ajv >= 5.1.2
