### ISSUE TITLE
Not compatible with ajv 5.2?

### ISSUE THREAD

**Issue by rolftimmermans** [epoberezkin/ajv-keywords#25]
I am using ajv-keywords@2.1.0 and ajv@5.2.2

The following code:

```
import ajv from "ajv"
import keywords from "ajv-keywords"

keywords(ajv)
```

produces:

```
  ajv.addKeyword('instanceof', defFunc.definition);
      ^

TypeError: ajv.addKeyword is not a function
    at defFunc (/Users/rolftimmermans/Code/tinify/framework/node_modules/ajv-keywords/keywords/instanceof.js:46:7)
```

Is ajv-keywords compatible with ajv 5? If not, that would be a shame since I currently need the `switch` keyword but it has been removed from ajv.

**Comment by epoberezkin** [comment]
You need to pass the instance of ajv. What package exports is a class, so you need

```
ajv = new Ajv
```

**Comment by rolftimmermans** [comment]
Of course! Thanks for clarifying.
