### ISSUE TITLE
Using switch in sub schema ?

### ISSUE THREAD

**Issue by Rmannn** [epoberezkin/ajv-keywords#26]
Hi, how to use switch in sub schema ? It's only working if switch is in the root schema.

exemple: 
- object1
    - object2
    - switch2 (not working)
- switch1

Maybe there is a way to use properties selector in the switch keyword that is at root position ?
like "object1.object2.something" ?

Thanks

**Comment by epoberezkin** [comment]
@Rmannn switch works in sub-schemas. Please post the full schema and the code that doesn't work, ideally via runkit.com.

**Comment by epoberezkin** [comment]
@Rmannn closing, please re-open with full info.

**Comment by Rmannn** [comment]
Sorry for my late answer, thank you. It's working.
