### ISSUE TITLE
Can't resolve absolute URI $ref in selectCases

### ISSUE THREAD

**Issue by byrneciaran** [epoberezkin/ajv-keywords#27]
I'm referencing a schema, bar.json, that sits in the same directory as my schema as follows:

```
"selectCases":{
  "foo": {
      "properties": {
        "id": {},
        "bar": {
          "$ref": "bar.json"
        }
      }
    }
}
```
I'm receiving the error:

`can't resolve reference bar.json from id #`

I thought that this absolute URI reference would work?

**Comment by byrneciaran** [comment]
Actually this is my fault, my $id was wrong!

**Comment by abeishekeeva** [comment]
How did you solve the problem with your $id?

**Comment by byrneciaran** [comment]
The name of my $id was wrong. It wasn't called "bar.json" :)
