### ISSUE TITLE
[keyword] if/then/else

### ISSUE THREAD

**Issue by epoberezkin** [epoberezkin/ajv-keywords#3]
https://github.com/json-schema-org/json-schema-spec/issues/180

**Comment by HotelDon** [comment]
I would prefer a containing keyword for these, so you can have multiple ifs for a single entry. Something like this, maybe?
````
"conditional": [
    {
        "if": {"$ref": "#/definitions/condition1"},
        "then": {"$ref": "#/definitions/schema1"},
        "else": {"$ref": '#/definitions/schema2"}
    },
   {
         "if": {"$ref": "#/definitions/condition2"},
        "then": {"$ref": "#/definitions/schema3"},
        "else": {"$ref": '#/definitions/schema4"}
    }
]   
````
The order of the array shouldn't impact whether data passes validation or not, so schema writers can focus on it having it make sense at first glance. 

If you only have need for one conditional statement,, then you could just skip the array entirely. 
````
"conditional":  {
         "if": {"$ref": "#/definitions/condition1"},
        "then": {"$ref": "#/definitions/schema1"},
        "else": {"$ref": '#/definitions/schema2"}
    }
````
