### ISSUE TITLE
Is it possible to extend the native types, e.g. string or apply keywords "globally" to all fields

### ISSUE THREAD

**Issue by agjs** [epoberezkin/ajv-keywords#345]
Hey guys. Sorry if the question isn't placed in the right repo, as I wasn't sure where to ask it.

Essentially, I'd like to know if it is possible to extend some of the native types with extra validation, so I don't have to repeat myself for nearly every single field.

For instance, in the project that I'm building, I'm not allowing profanity words, nor e.g. HTML or any special characters for none of the fields (inputs) in the project. I'm currently adding a lot of redundant code, because for nearly every field that maps to some input, I have to add both of those custom keywords (hasProfanity and nonHTML).

Is there a way to e.g. just extend the string field, or simply "globally" apply those validators to every single field, without needing to add them manually.

Thanks a bunch in advance!

**Comment by agjs** [comment]
Anyone that can answer this, please?

**Comment by epoberezkin** [comment]
I am afraid it won't be possible - I have always resisted the ideas to change the definitions of the standard keywords, as it would undermine schemas as a cross-platform standardised language that can be understood by other people. So when readers can see some non-standard keyword, they can figure out what it does by searching for it in the code, but if suddenly `type: string` does something different to what it normally does, it would be very surprising... To avoid repetitions you can use references and definitions, but initially you'd have to replace `type: string` with something like `$ref: defs#userProvidedString` or similar where it is appropriate, but you wouldn't need to do it for closed enumerations for example...

**Comment by agjs** [comment]
> I am afraid it won't be possible - I have always resisted the ideas to change the definitions of the standard keywords, as it would undermine schemas as a cross-platform standardised language that can be understood by other people. So when readers can see some non-standard keyword, they can figure out what it does by searching for it in the code, but if suddenly `type: string` does something different to what it normally does, it would be very surprising... To avoid repetitions you can use references and definitions, but initially you'd have to replace `type: string` with something like `$ref: defs#userProvidedString` or similar where it is appropriate, but you wouldn't need to do it for closed enumerations for example...

Hi @epoberezkin,

Extending the `native` type was just a semi-random example, but I believe that you have missed a point here, or maybe I wasn't clear enough.

Let me lay out the example. In the project that I'm building, we have two custom keywords that we want to apply to every single input.

`hasProfanity` and `nonHTML`

In simple words, there isn't a single input in the entire project, that allows profanity or HTML as an input. Due to this, I need a way to `globally` apply those, so I don't have to write redundant, duplicated code for every single type in every single schema.

While I agree with the sentiment that native types shouldn't be `mutated`, there should be a way to globally apply rules to the entire schema if one needs to do such a thing.
