### ISSUE TITLE
Can't get simple removeAddtional, if-else, properties combination to work

### ISSUE THREAD

**Issue by martingronlund** [epoberezkin/ajv-keywords#36]
Here is a file that depends on the `ajv` and `ajv-keywords` packages.
I don't know if this is a keywords-related feature or not.

I expect this to output `{ transition: 'FOO, transitionDuration: 30 }`
Am I at fault?
What should I change?

In short I'm looking for a simple and readable way for users to add properties.
Any help is appreciated.

```
const Ajv = require('ajv')

const schema = {
  properties: {
    transition: {
      type: 'string',
      enum: ['FOO', 'BAR']
    }
  },
  allOf: [
    {
      if: {
        properties: {
          transition: {
            const: 'FOO'
          }
        }
      },
      then: {
        properties: {
          transitionDuration: {
            type: 'number'
          }
        }
      }
    }
  ]
}

const ajv = Ajv({ removeAdditional: 'all' })
require('ajv-keywords')(ajv, 'if')

const validate = ajv.compile(schema)
const data = { transition: 'FOO', transitionDuration: 30 }
validate(data)
console.log(data)
```

**Comment by epoberezkin** [comment]
That's how it is supposed to work by the spec, see https://github.com/epoberezkin/ajv/blob/master/FAQ.md#additional-properties-inside-compound-keywords-anyof-oneof-etc for more information

**Comment by martingronlund** [comment]
Sorry, have looked at this for hours...
How would you go about removing properties conditionally?

Can you show a minimal example of toggling transitionDuration with the value of transition?

**Comment by martingronlund** [comment]
Actually found something that worked.
> You can use { "not": { "required": ["account"] } } to explicitly prohibit property account.

Thanks for your amazing work on this library. So happy now 👍
