### ISSUE TITLE
Validation always fail when additionalProperties set to false

### ISSUE THREAD

**Issue by sachintharajith** [epoberezkin/ajv-keywords#46]
Hi,
I want to send a message to the end user if he has used any additional fields other than allowed set of fields. I use additionalProperties to false. Following is my json schema.
```
{
    type: "object",
    additionalProperties : false,
    properties: {
        question: {
            type: "string"
        },
        series: {
            type: "string",
            enum: ["all","first","last"]
        }
    }
}
```

I use ajv NPM in nodejs and for all the valid requests it returns following message.

```
{
"keyword": "additionalProperties",
"dataPath": "",
"schemaPath": "#/additionalProperties",
"params": {
"additionalProperty": "__proto__"
},
"message": "should NOT have additional properties"
}
```

I'm not sure whether I'm using the correct approach to solve my issue. I used ownProperties to true, but it didn't help.

I think if we have an option to omit the inherited field (proto) that would be really helpful.

**Comment by epoberezkin** [comment]
If you didn't resolve it yet, please submit the issue to ajv repo. Please answer all the questions in the issue template.
