### ISSUE TITLE
dynamicDefaults signature should be like default and it would work with required

### ISSUE THREAD

**Issue by muayyad-alsadi** [epoberezkin/ajv-keywords#50]
a typical default is like like `bar/baz` below

```var schema = {
  "type": "object",
  "properties": {
    "foo": { "type": "number" },
    "bar": { "type": "string", "default": "baz" }
  },
  "required": [ "foo", "bar" ]
};
```

`dynamicDefaults` should be 

```var schema = {
  "type": "object",
  "properties": {
    "foo": { "type": "number" },
    "bar": { "type": "string", "dynamicDefaults": "timestamp" }
  },
  "required": [ "foo", "bar" ]
};
```

and it should also work with required

your docs says it does not

> The properties used in dynamicDefaults should not be added to required keyword (or validation will fail), because unlike default this keyword is processed after validation.

**Comment by epoberezkin** [comment]
see the example in https://github.com/epoberezkin/ajv-keywords#dynamicdefaults - the keyword is defined to be used on the parent object level.

> and it should also work with required

The spec explicitly says otherwise.

Related to https://github.com/epoberezkin/ajv/issues/684

**Comment by muayyad-alsadi** [comment]
is this an implantation choice in `ajv` or by jsonschema standard ?

I know how to use dynamicdefaults. but I believe it should be similar to standard defaults
