### ISSUE TITLE
Add `Promise` support to `instanceof`

### ISSUE THREAD

**Issue by jbottigliero** [epoberezkin/ajv-keywords#52]
While working on webpack/webpack-cli#240 the need for validating a `Promise` came up. It looks like the only way to use `instanceof` to validate this constructor type is by augmenting the `CONSTRUCTORS` manually (similar to adding a custom constructor). 

It seems like the `Promise` constructor could be supported in a similar manner as `Buffer`.

I've opened a PR proposing this update #51 – looking forward to the discussion, thanks!

**Comment by epoberezkin** [comment]
#51 merged, will release.

**Comment by epoberezkin** [comment]
in [3.1.0](https://github.com/epoberezkin/ajv-keywords/releases/tag/v3.1.0)
