### ISSUE TITLE
npm ERR! peer dep missing: ajv@^6.0.0, required by ajv-keywords@3.1.0

### ISSUE THREAD

**Issue by sbwfnyiiiu** [epoberezkin/ajv-keywords#56]
Can  you tell me how to fix this ? the "nmp ls -g" output as in the enclosed file a.txt.
[a.txt](https://github.com/epoberezkin/ajv-keywords/files/1734821/a.txt)
 Thanks.

**Comment by lanjiabin90** [comment]
same error

**Comment by epoberezkin** [comment]
See https://github.com/epoberezkin/ajv/issues/708#issuecomment-368344718

**Comment by luxcium** [comment]
Is this issue include the problem I have in [#74](https://github.com/epoberezkin/ajv-keywords/issues/74) about the circular problem  of :
 
1. installing ajv@^**6.0.0**  gives this error -> ajv-keywords@2.1.1 requires a peer of ajv@^**5.0.0**

2. and installing ajv@^**5.0.0**   gives this error -> ajv-keywords@3.2.0 requires a peer of ajv@^**6.0.0**
