### ISSUE TITLE
regexp doesn't support unicode flag if not a schema

### ISSUE THREAD

**Issue by JaredCE** [epoberezkin/ajv-keywords#65]
This https://github.com/epoberezkin/ajv-keywords/blob/master/keywords/regexp.js#L14 doesn't take into account the unicode (u) flag when using a pattern as a string rather than an object

`"regexp": "/^((?!\\b(?:CC|Closed?(\\u{002D}|\\u{2010}|\\u{2212}|\\u{2012}|\\u{2013}|\\u{2014}|\\u{2015})Caption(?:ed)?|14\\s?(x|:|\\u{2015})\\s?9|9\\s?(x|:|\\u{2015})\\s?14|16\\s?(x|:|\\u{2015})\\s?9|9\\s?(x|:|\\u{2015})\\s?16|4\\s?(x|:|\\u{2015})\\s?3|3\\s?(x|:|\\u{2015})\\s?4|\\d+\\s?fps|EPK|Video|Clip|Press\\s(?:Kit|Pack))\\b).)*$/u` would fail whereas

```
"regexp": {
  "pattern": "^((?!\\b(?:CC|Closed?(\\u{002D}|\\u{2010}|\\u{2212}|\\u{2012}|\\u{2013}|\\u{2014}|\\u{2015})Caption(?:ed)?|14\\s?(x|:|\\u{2015})\\s?9|9\\s?(x|:|\\u{2015})\\s?14|16\\s?(x|:|\\u{2015})\\s?9|9\\s?(x|:|\\u{2015})\\s?16|4\\s?(x|:|\\u{2015})\\s?3|3\\s?(x|:|\\u{2015})\\s?4|\\d+\\s?fps|EPK|Video|Clip|Press\\s(?:Kit|Pack))\\b).)*$",
  "flags": "u"
}
```

passes.

**Comment by epoberezkin** [comment]
Should be added.

**Comment by jay1337** [comment]
Any update ?
Using this flag is recommended: https://eslint.org/docs/rules/require-unicode-regexp

**Comment by epoberezkin** [comment]
PR is welcome, it's a simple change here: https://github.com/epoberezkin/ajv-keywords/blob/master/keywords/regexp.js#L14
