### ISSUE TITLE
peer dependencies issues

### ISSUE THREAD

**Issue by luxcium** [epoberezkin/ajv-keywords#74]
if I install v. 6 myself I receive the error message that I must install the v. 5 and its not leting me install the version 5 without prompting me of the first probleme 

ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.

ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.

**Comment by epoberezkin** [comment]
duplicate of https://github.com/epoberezkin/ajv-keywords/issues/56
