### ISSUE TITLE
Custom Keywords Meta Schema

### ISSUE THREAD

**Issue by imikemiller** [epoberezkin/ajv-keywords#77]
Do you have a meta schema that includes your custom keywords by any chance?

I would like to validate schemas themselves and intend to allow your custom keyword extensions when creating schemas. 

Essentially I am looking for the equivalent to this meta schema: http://json-schema.org/draft-07/schema

Thanks for the excellent library!

**Comment by epoberezkin** [comment]
Keywords definitions include fragments of meta-schemas for each one - they can be used in any combinations. Also, extending meta-schemas is a difficult in JSON-Schema (see how hyperschema metaschema looks for example).
