### ISSUE TITLE
Keyword 'transform' doesn't perform before other validations

### ISSUE THREAD

**Issue by magnuslim** [epoberezkin/ajv-keywords#78]
Per the doc:
> This keyword allows a string to be modified **before validation**.

But when I ran the code below:
```js
const Ajv = require('ajv');
const ajv = new Ajv();
require('ajv-keywords')(ajv, ['transform']);

const schema = {
  type: 'array',
  items: {
    type:'string',
	transform: ['trim'],
	format: 'email'
  }
};

const data = [' hello@hi.com '];
console.log(ajv.validate(schema, data));
console.log(data);
```

I got:
```
false
[ ' hello@hi.com ' ]
```

The keyword `format` performed before the `transform`.

**Comment by epoberezkin** [comment]
To enforce specific order you need to use allOf. Within one schema custom keywords are evaluated after standard.

**Comment by paps** [comment]
Hi, can you be a little more specific please? I didn't understand your answer.

In my schema I use $ref to another schema that uses the `transform` keyword. How do I make sure `trim()` is done before validation? Thanks
