### ISSUE TITLE
Feature request: allRequired: true for objects

### ISSUE THREAD

**Issue by m4recek** [epoberezkin/ajv-keywords#79]
Hi,
we are using schemas for strict validation and it is too easy to not add properties into `required` array resulting in bugs. I want to suggest a keyword suggestion which will make this usecase much easier.

*Keyword Suggestion:* `requireAll: true` for objects, which will force all listed properties to be required in the object

Optionally it would be nice to have a global switch for `requireAll` which will force it on every validated object unless it has `requireAll: false` in its definition.

**Comment by epoberezkin** [comment]
requireAll as keyword is ok.

**Comment by m4recek** [comment]
Thank you for doing this, I have just used it throughout our codebase and immediately found few omitted properties. 
Excellent work ;-)

**Comment by epoberezkin** [comment]
Seems a good candidate for the spec. Other ...required ideas are just syntax sugar, but this one avoids duplicating the list of properties if they are all required.

**Comment by nikeline** [comment]
Hello. I would like to clarify.
If we use the keyword allRequired: true, for the scheme
const schema = {
    type       : 'object',
    properties : {
        
        foo : { type: 'number' },
        bar : { type: 'number' },
    },      
    allRequired          : true,
    additionalProperties : false,
};

Then when comparing with this object, will there be an error?
const validData = {
    foo : 1,
};

**Comment by nikeline** [comment]
Understood, thanks
