### ISSUE TITLE
warning "ajv-keywords@2.0.1-beta.1" has incorrect peer dependency "ajv@>=5.0.3-beta.0".

### ISSUE THREAD

**Issue by develar** [epoberezkin/ajv-keywords#8]
Could you please publish ajv-keywords with updated ajv requirement? Latest ajv `5.0.4-beta.0`.

**Comment by develar** [comment]
https://github.com/electron-userland/electron-builder/issues/1344

**Comment by epoberezkin** [comment]
@develar I thought it would match... Will update

**Comment by develar** [comment]
@epoberezkin Please see https://yarnpkg.com/lang/en/docs/dependency-versions/#toc-pre-release-tags

> For example, the range >=3.1.4-beta.2 would match 3.1.4-beta.2 or 3.1.4-beta.12, but would not match 3.1.5-beta.1 even though it is technically “greater than or equal to” (>=) the 3.1.4-beta.2 version.

**Comment by epoberezkin** [comment]
in 2.0.1-beta.2
