### ISSUE TITLE
v3.3.0 breaks `transform` keyword

### ISSUE THREAD

**Issue by willfarrell** [epoberezkin/ajv-keywords#83]
`schema` in an array and in v3.3.0 it assumes it's a string causing:
```
TypeError: Cannot read property 'hash' of undefined
    at Object.toEnumCase (transform.js:21)
    at g.eval (transform.js:57)
    at validate (eval at w (ajv.min.js:NaN), <anonymous>:3:15305)
```

v3.2.0 = https://github.com/epoberezkin/ajv-keywords/blob/v3.2.0/keywords/transform.js#L14
v3.3.0 = https://github.com/epoberezkin/ajv-keywords/blob/v3.3.0/keywords/transform.js#L33

**Comment by epoberezkin** [comment]
Looks like I did it: 
https://github.com/epoberezkin/ajv-keywords/commit/3c1fda424805fcbfd0067e2dd624af936cd74a4d

@willfarrell could you maybe add PR with the test case(s) that pass in 3.2 and fail in 3.3? I would fix my “improvement” over the weekend then. Thank you.
