### ISSUE TITLE
`uniqueItemProperties` with ignoreCase

### ISSUE THREAD

**Issue by pushpa446** [epoberezkin/ajv-keywords#96]
const Ajv = require('ajv');
require('ajv-keywords')(ajv, 'uniqueItemProperties');

const schema = { uniqueItemProperties: ['id', 'name'] };

var data = [
{ id: 1, name: 'taco' },
{ id: 2, name: 'TACO' }, // duplicate "name"
{ id: 3, name: 'salsa' },
];
const validate = ajv.compile(schema);

I would like to make the `name` field to be unique but with ignoring case. 
Any way to do this?

**Comment by epoberezkin** [comment]
You could use "transform" keyword in this package.

**Comment by pushpa446** [comment]
But `transform` changes the data, which I don't want to.
