### ISSUE TITLE
validating duplicate objects in array not working

### ISSUE THREAD

**Issue by nipun-tw** [epoberezkin/ajv-keywords#98]
I want to check if any of the objects inside array is duplicate.
I'm using anyOf on all the keys, so that either of them is unique, i will get a unique object. 

It consoles out as false.

```
const ajv = require("ajv")();
require("ajv-keywords")(ajv, "uniqueItemProperties");

const schema = {
  type: "array",
  anyOf: [
    { uniqueItemProperties: ["type"] },
    { uniqueItemProperties: ["name"] },
    { uniqueItemProperties: ["make"] }
  ]
};

var data = [
  {
    type: "car",
    name: "baleno",
    make: "suzuki"
  },
  {
    type: "car",
    name: "baleno",
    make: "toyota"
  },
  {
    type: "car",
    name: "corolla",
    make: "ford"
  },
  {
    type: "car",
    name: "baleno",
    make: "ford"
  },
  {
    type: "car",
    name: "corolla",
    make: "toyota"
  },

];
const validate = ajv.validate(schema, data);
console.log("validate: " + validate);
```

**Comment by nipun-tw** [comment]
Is my understanding right that
either of "type", "make" and "name"  should be unique by themselves ? 
like there cannot be any instance of same "name" or "type" or "make" which are same.

**Comment by epoberezkin** [comment]
there is a standard uniqueItems keyword - you don't need this one. uniqueItemProperties exists to duplicate one or more properties that should be unique across all items (e.g. item ID).

**Comment by caub** [comment]
@epoberezkin Would it be possible to mutate the data to make the unqiue field unique, I mean an option like

```js
const ajv = new Ajv({ removeDuplicates: true });
const data = { fruits: [''orange', 'fig', 'orange'] };
ajv.validate({ fruits: { type: 'array', items: [ {type: 'string'}], uniqueItems: true} }, data)
data // { fruits: [''orange', 'fig'] };
```
Maybe I can achieve this with a plugin?
